### ISSUE TITLE
Index.html missing doctype declaration

### ISSUE THREAD

**Issue by nicksuch** [Anansi86/Anansi86.github.io#1]
Hey @Anansi86 (or should I say, Super Shawn) - nice work with this page! Only thing I see to fix is that you're currently missing a doctype declaration. See notes here:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fanansi86.github.io%2F

**Comment by Anansi86** [comment]
Caught your email. I fixed the error, and pushed it back on github.
